pipeline {
	agent any 
	stages {
	stage ('Checkout') {
	steps {
		sh 'checkout scm'
		}
		}
		

	stage ('Build') {
		steps {
		sh 'nuget restore SolutionName.sln'
		bat "\"${tool 'MSBuild'}\" SolutionName.sln /p:Configuration=Release /p:Platform=\"Any CPU\" /p:ProductVersion=1.0.0.${env.BUILD_NUMBER}"
}
}
	stage ('Archive') {
	steps {
		sh 'ProjectName/bin/Release/**'
		}
		}
		}
		}

